# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TheToWatch' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TheToWatch
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Firestore', '~> 5.20.1'

  target 'TheToWatchTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TheToWatch-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TheToWatch-tvOS

  target 'TheToWatch-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
